// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '// 'Navbar copy': typeof import('./src/components/Navbar copy.vue')['default']
    '// Alerts': typeof import('./src/components/Alerts.vue')['default']
    '// AppButton': typeof import('./src/components/@core/AppButton.vue')['default']
    '// AppColorInput': typeof import('./src/components/@core/AppColorInput.vue')['default']
    '// AppImage': typeof import('./src/components/@core/AppImage.vue')['default']
    '// AppImageDropzone': typeof import('./src/components/@core/AppImageDropzone.vue')['default']
    '// AppLabelsPicker': typeof import('./src/components/@core/AppLabelsPicker.vue')['default']
    '// AppLoader': typeof import('./src/components/@core/AppLoader.vue')['default']
    '// AppPageHeading': typeof import('./src/components/@core/AppPageHeading.vue')['default']
    '// BoardCard': typeof import('./src/components/BoardCard.vue')['default']
    '// BoardDragAndDrop': typeof import('./src/components/BoardDragAndDrop.vue')['default']
    '// BoardMenu': typeof import('./src/components/BoardMenu.vue')['default']
    '// Button': typeof import('./src/components/@custom/Button.vue')['default']
    '// Drawer': typeof import('./src/components/Drawer.vue')['default']
    '// Footer': typeof import('./src/components/Footer.vue')['default']
    '// JdzButton': typeof import('./src/components/@custom/JdzButton.vue')['default']
    '// Navbar': typeof import('./src/components/Navbar.vue')['default']
    '// RouterLink': typeof import('vue-router')['RouterLink']
    '// RouterView': typeof import('vue-router')['RouterView']
    '// TaskCard': typeof import('./src/components/TaskCard.vue')['default']
    '// TaskCreator': typeof import('./src/components/TaskCreator.vue')['default']
    '// TaskLabel': typeof import('./src/components/TaskLabel.vue')['default']
    '// TheNavbar': typeof import('./src/components/TheNavbar.vue')['default']
    Alerts: typeof import('./src/components/Alerts.vue')['default']
    AppButton: typeof import('./src/components/@core/AppButton.vue')['default']
    AppColorInput: typeof import('./src/components/@core/AppColorInput.vue')['default']
    AppImage: typeof import('./src/components/@core/AppImage.vue')['default']
    AppImageDropzone: typeof import('./src/components/@core/AppImageDropzone.vue')['default']
    AppLabelsPicker: typeof import('./src/components/@core/AppLabelsPicker.vue')['default']
    AppLoader: typeof import('./src/components/@core/AppLoader.vue')['default']
    AppPageHeading: typeof import('./src/components/@core/AppPageHeading.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    JdzButton: typeof import('./src/components/@custom/JdzButton.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
